package cluster;

import js.base.BaseObject;
import js.file.Files;
import js.parsing.DFA;
import js.parsing.Lexer;
import sample.SampleMain;
//import match.MatchMain;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import static js.base.Tools.*;
import static cluster.MatchUtil.*;

public class CsvReader extends BaseObject {

  public void parse(File file) {
    parse(Files.readString(file));
  }

  public void parse(String csvContent) {
    prepareDfas();
    mColumnNames = arrayList();
    mRows = arrayList();

    // Ensure file ends with a single linefeed
    csvContent = csvContent.strip() + "\n";

    var s = new Lexer(sCsvDfa).withNoSkip().withText(csvContent);

    // Read column headers
    while (true) {
      var columnName = parseString(stripQuotes(readValueBeforeCommaOrNewline(s)));
      mColumnNames.add(columnName);
      if (s.readIf(T_CR))
        break;
      s.read(T_COMMA);
    }

    int numColumns = mColumnNames.size();

    while (s.hasNext()) {
      List<String> columnContents = new ArrayList<>(numColumns);
      for (int i = 0; i < numColumns; i++) {
        var content = readValueBeforeCommaOrNewline(s);
        var expected = (i + 1 < numColumns) ? T_COMMA : T_CR;
        s.read(expected);
        if (ISSUE_12 && false)
          content = trimDoubles(content);
        columnContents.add(content);
      }
      mRows.add(columnContents);
    }
  }

  public List<String> columnNames() {
    assertParsed();
    return mColumnNames;
  }

  public int findColumn(String name) {
    return columnNames().indexOf(name);
  }

  public List<List<String>> rows() {
    assertParsed();
    return mRows;
  }

  // Since not all values are put in quotes, it's possible for a field
  // to be empty; so a comma can be followed immediately by another comma or cr.
  //
  // So if we expect a value, we have to optionally read that value, vs return
  // an empty string
  //
  private String readValueBeforeCommaOrNewline(Lexer s) {
    if (s.peekIf(T_COMMA) || s.peekIf(T_CR)) {
      return "";
    }
    return s.read(T_VALUE).text();
  }

  private void assertParsed() {
    if (mColumnNames == null)
      throw new IllegalStateException("csv file has not been parsed yet");
  }

  private boolean parsed() {
    return mColumnNames != null;
  }

  private List<String> mColumnNames;
  private List<List<String>> mRows;

  // ------------------------------------------------------------------
  // DFA
  // ------------------------------------------------------------------

  // Token Ids generated by 'dev dfa' tool (DO NOT EDIT BELOW)
  public static final int T_CR = 0;
  public static final int T_COMMA = 1;
  public static final int T_VALUE = 2;
  // End of token Ids generated by 'dev dfa' tool (DO NOT EDIT ABOVE)

  private static void prepareDfas() {
    if (sCsvDfa == null) {
      todo("replace with string constant");
      sCsvDfa = DFA.parse(Files.readString(SampleMain.class, "csv.dfa"));
    }
  }

  private static DFA sCsvDfa;

}
