package cluster;

public class LineStringTokens {
  // Token Ids generated by 'dev dfa' tool (DO NOT EDIT BELOW)
  public static final int LS_WS = 0;
  public static final int LS_LINESTRING = 1;
  public static final int LS_ENDLINESTRING = 2;
  public static final int LS_NUMBER = 3;
  public static final int LS_COMMA = 4;
  // End of token Ids generated by 'dev dfa' tool (DO NOT EDIT ABOVE)

}
